<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Jezz" failures="1" tests="4" name="PIM-Section-Test" time="84.331" errors="0" timestamp="2025-08-24T13:02:48 WIB">
  <testcase classname="com.example.java.testcases.PIMTest" name="testAddNewEmployee" time="12.6"/>
  <testcase classname="com.example.java.testcases.PIMTest" name="testCheckEmployeeOnEmployeeList" time="2.306"/>
  <testcase classname="com.example.java.testcases.PIMTest" name="testDeleteEmployeeOnTheEmployeeList" time="18.536">
    <failure type="java.lang.AssertionError" message="Employee with first name &amp;apos;Ronnie&amp;apos; still appears in the list after deletion. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Employee with first name 'Ronnie' still appears in the list after deletion. expected [false] but found [true]
at com.example.java.testcases.PIMTest.testDeleteEmployeeOnTheEmployeeList(PIMTest.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteEmployeeOnTheEmployeeList -->
  <testcase classname="com.example.java.testcases.PIMTest" name="testNavigateToPIM" time="1.737"/>
</testsuite> <!-- PIM-Section-Test -->
